customer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^restaurant/(\d+)/order$", views.order, name="order"),
    url(r"^orderitem/(\d+)/confirm$", views.confirm_orderitem, name="confirm_orderitem"),
    url(r"^orderitem/(\d+)/remove", views.remove_orderitem, name="remove_orderitem"),
    url(r"^order/(\d+)/checkout$", views.checkout, name="checkout"),
    url(r"^order/(?P<order_id>\d+)/pay/(?P<payment_method_id>\d+)$", views.pay, name="pay"),
    url(r"^order/(\d+)/feedback$", views.feedback, name="feedback"),
    url(r"^restaurant/(?P<restaurant_id>\d+)/check-in$", views.check_in, name="check_in"),
    url(r"^restaurant/(?P<restaurant_id>\d+)/order/(?P<item_id>\d+)$", views.order_item, name="order_item"),
    url(r"^restaurant/(\d+)/menu$", views.menu, name="menu"),

    # AJAX handlers
    url(r"^restaurant/(?P<id>\d+)/check-for-order$", views.check_for_open_order, name="check_for_open_order"),
    url(r"^restaurant/search$", views.search, name="restaurant_search"),

]

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r"^register$", views.register, name="register"),
    url(r"^profile$", views.profile, name="profile"),
    url(r"^profile/delete$", views.profile_delete, name="profile_delete"),
    url(r"^logout$", views.logout_user, name="logout"),

    # AJAX stuff
    url(r"^profile/menu_languages/ordering$", views.set_menu_language_order, name="set_menu_language_order"),
]

smartmenu/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="accounts")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^main/', include('main.urls', namespace="main")),
    url(r'^customer/', include('customer.urls', namespace="customer")),
    url(r'^waiter/', include('waiter.urls', namespace="waiter")),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('customer:index'), permanent=False)),
)

waiter/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.index, name="waiter"),
    url(r"^restaurant/(?P<id>\d+)$", views.for_restaurant, name="for_restaurant"),
    url(r"^restaurant/(?P<id>\d+)/qr/read$", views.read_qr, name="read_qr"),
    url(r"^checkin/(?P<table_id>\d+)/(?P<user_id>\d+)$", views.checkin_customer, name="checkin_customer"),
    url(r"^table/choose", views.choose_table, name="choose_table"),
    url(r"^checkout/(?P<id>\d+)", views.checkout, name="checkout"),
]

customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from main.models import *
from main.forms import *
import json
import os
import qrcode


def index(request):
    # find out if the logged-in user is also manager or waiter
    manager_at = []
    waiter_at = []
    if request.user.is_authenticated():
        roles = UserRole.objects.filter(user=request.user)
        manager_at = filter(lambda x: x.role.name == UserRole.MANAGER, roles)
        waiter_at = filter(lambda x: x.role.name == UserRole.WAITER, roles)

    return render(request, "customer/index.html", {
        "hide_logo": True,
        "manager_at": manager_at,
        "waiter_at": waiter_at,
    })


def search(request):
    """search in a restaurant's name based on `q` parameter"""
    # XXX replace with a more robust search in case of many restaurants in the system

    result = []
    if "q" in request.GET:
        result = []
        q = request.GET["q"]
        # search the restaurant's name
        restaurants = Restaurant.objects.filter(name__icontains=q)
        for r in sorted(restaurants, lambda x, y: cmp(x.name, y.name)):
            result.append({
                "id": r.id,
                "name": r.name,
                "street": r.address.street,
                "street_no": r.address.street_no,
                "city": r.address.city,
                "zip_code": r.address.zip,
                "country": r.address.country.code,
            })
    return HttpResponse(json.dumps(result), content_type='application/json')


@login_required
def order_item(request, restaurant_id, item_id):
    """order an item for the logged-in user at a restaurant.
    """
    item = get_object_or_404(Item, id=item_id)
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)

    l = _get_menu_language(request, restaurant.menu)
    i18n = get_object_or_404(ItemI18n, language=l, item=item)

    # create order
    order = Order.for_user(request.user, restaurant)
    order.add_item(i18n)

    return redirect("customer:menu", restaurant.id)


@login_required
def check_in(request, restaurant_id):
    """check-in the logged-in user at restaurant
    """
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)

    # is an order already open?
    if Order.for_user(request.user, restaurant) is not None:
        return redirect("customer:menu", restaurant.id)

    _create_qr_code(request.user, restaurant)

    # wait for an signal, i.e. for an order to be opened (from waiter)
    return render(request, "customer/check-in.html", {
        "restaurant": restaurant})


@login_required
def check_for_open_order(request, id):
    """check if for given user and restaurant an order objects exists,
    i.e. a waiter has logged in the user"""
    restaurant = get_object_or_404(Restaurant, id=id)
    order = Order.for_user(request.user, restaurant, True)
    return HttpResponse("%s" % (order and order.id or ""))


def menu(request, id):
    """render a menu for a restaurant
    """
    restaurant = get_object_or_404(Restaurant, id=id)
    lang = _get_menu_language(request, restaurant.menu)
    order = Order.for_user(request.user, restaurant)
    prof = UserProfile.for_user(request.user)

    # store URL in case somebody wants to sign in and return back
    request.session["next"] = request.build_absolute_uri()

    # create a localized category tree with items and allergens.
    categories = []
    for c18n in restaurant.menu.categories_for_language(lang):
        cat_data = []
        for i18n in c18n.category.items_for_language(lang):
            allergens = []
            traces = []
            for itemallergen in i18n.item.itemallergen_set.all():
                a18n = get_object_or_404(AllergenI18n, language=lang, allergen=itemallergen.allergen)
                warn = prof and a18n.allergen in prof.allergens.all()
                if itemallergen.traces:
                    traces.append((a18n, warn))
                else:
                    allergens.append((a18n, warn))
            cat_data.append((i18n.item, i18n, allergens, traces))
        categories.append((c18n, cat_data))

    # available menu languages
    languages = [restaurant.menu.language]
    languages.extend(restaurant.menu.translations.all())

    return render(request, "customer/menu.html", {
        "language": lang,
        "menu_languages": languages,
        "categories": categories,
        "restaurant": restaurant,
        "order": order,
        "all_allergens": AllergenI18n.objects.filter(language=lang),
    })


def order(request, id):
    """render the summary page for an order
    """
    restaurant = get_object_or_404(Restaurant, id=id)
    order = Order.for_user(request.user, restaurant)
    lang = _get_menu_language(request, restaurant.menu)

    # guards
    if not order:
        raise Http404("Invalid order")

    # collect confirmed and not yet confirmed order items
    confirmed = []
    unconfirmed = []
    for oi in order.orderitem_set.all():
        oi18n = get_object_or_404(ItemI18n, language=lang, item=oi.item)
        if oi.confirmed:
            confirmed.append((oi, oi18n))
        else:
            unconfirmed.append((OrderItemForm(instance=oi), oi18n))

    return render(request, "customer/order.html", {
        "restaurant": restaurant,
        "order": order,
        "unconfirmed": unconfirmed,
        "confirmed": confirmed,
    })


@login_required
def confirm_orderitem(request, id):
    """confirm an item on the order
    """
    oi = get_object_or_404(OrderItem, id=id)

    # update order item
    form = OrderItemForm(request.POST, instance=oi)
    oi.confirmed = timezone.now()
    form.save()

    return redirect("customer:order", oi.order.table.restaurant.id)


@login_required
def remove_orderitem(request, id):
    """remove an item from the order
    """
    oi = get_object_or_404(OrderItem, id=id)
    oi.delete()
    return redirect("customer:order", oi.order.table.restaurant.id)


def _get_menu_language(request, menu):
    """return the actual menu language
    """
    result = menu.language

    # first obtain the language from URI
    lang = request.GET.get("l", None)
    if lang:
        result = Language.objects.filter(abbr=lang).first()
    else:
        # if not found, then obtain language form his browser's settings
        lang = Language.get_current()
        if lang in menu.translations.all():
            result = lang
            # print "get_menu_language for %s: %s" % (user, result)
    return result


@login_required
def checkout(request, id):
    """checkout the user. This closes the order and prompts the user to pay
    """
    order = get_object_or_404(Order, id=id)
    payment_methods = order.table.restaurant.payment_method.all()

    # if order is NOT empty
    if not order.total(confirmed_only=True):
        restaurant = order.table.restaurant
        order.checkout = timezone.now()
        order.save()
        return redirect("customer:menu", restaurant.id)

    return render(request, "customer/checkout.html", {
        "order": order,
        "restaurant": order.table.restaurant,
        "payment_methods": payment_methods,
    })


@login_required
def feedback(request, id):
    order = get_object_or_404(Order, id=id)

    # is there feedback posted?
    if request.POST:
        oi_id = request.POST.get("id")
        oi = get_object_or_404(OrderItem, id=oi_id)
        if Review.objects.filter(orderitem=oi).first():
            raise Http404("Review already exists for OrderItem (%d)" % oi.id)
        if oi.order.user != request.user:
            raise Http404("Requested OrderItem (%d) doesn't belong to you" % oi.id)
        rating = request.POST.get("rating")
        text = request.POST.get("text")
        # create review objects and save
        r = Review()
        r.text = text
        r.rating = rating
        r.orderitem = oi
        r.user = request.user
        r.save()

    # collect all unique items in the order
    orderitems = {}
    for oi in order.orderitem_set.all():
        orderitems[oi.item] = oi

    orderitems = sorted(orderitems.values(), lambda x, y: cmp(hasattr(x, "review"), hasattr(y, "review")))

    return render(request, "customer/feedback.html", {
        "order": order,
        "orderitems": orderitems,
        "restaurant": order.table.restaurant,
    })


@login_required
def pay(request, order_id, payment_method_id):
    order = get_object_or_404(Order, id=order_id)
    pm = get_object_or_404(PaymentMethod, id=payment_method_id)

    # checking for invalid logic
    payment = Payment.objects.filter(order=order).first()
    if payment:
        raise Http404("Order %d already paid for (Payment.id=%d)." % (order.id, payment.id))

    # do pay
    payment = Payment()
    payment.currency = order.table.restaurant.menu.currency
    payment.amount = order.total_confirmed()
    payment.order = order
    payment.method = pm
    payment.save()

    # XXX do the checkout. this is for demo only. in production this will be done by waiter after paying
    order.checkout = timezone.now()
    order.save()

    return render(request, "customer/paid.html", {
        "restaurant": order.table.restaurant,
        "order": order,
    })


def _get_logo_link(request):
    """return the link to be used in the logo (restaurant's name in the header)"""
    p = unicode(request.path)
    for pat in ("customer", "waiter", "manager"):
        if p.find("/%s" % pat) >= 0:
            return "%s:index" % pat
    assert 0


def _create_qr_code(user, restaurant):
    """create a QR code used for check-in by the waiter
    """
    code = "%d:%d" % (user.id, restaurant.id)
    img = qrcode.make(code)
    # save to file
    path = os.path.join(settings.MEDIA_ROOT, "qr")
    if not os.path.exists(path):
        os.mkdir(path)
    img_path = os.path.join(path, "%d.png" % user.id)

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from main.forms import *


def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            # create user and his profile
            user = form.save()
            user.set_password(user.password)
            user.save()
            profile = UserProfile.for_user(user)
            profile.user = user
            profile.save()
            # auth created user
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'],
                                )
            login(request, user)
            return redirect("main:profile")
    else:
        form = UserForm()
    return render(request, 'main/register.html', {"userform": form})


@login_required
def set_menu_language_order(request):
    """set the ordering field for languages"""
    profile = UserProfile.for_user(request.user)
    order = request.POST.get("menu_language_order")
    profile.menu_language_order = order
    profile.save()
    return HttpResponse("")


@login_required
def profile_delete(request):
    if request.POST and "_delete" in request.POST:
        UserProfile.for_user(request.user).delete()
        request.user.delete()
        return redirect("customer:index", next=None)
    return render(request, "main/profile_delete.html")


@login_required
def profile(request):
    # default form data (GET)
    # find all orders that are finished (check_out) and sort by latest checkin date
    orders = Order.objects.filter(user=request.user, checkout__isnull=False).order_by("-checkin")

    lang = Language.get_current()
    form = UserProfileForm(request.user, lang)

    # is there data to save? (POST)
    if request.POST:
        form = UserProfileForm(request.user, lang, request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:profile")

    result = render(request, "main/profile.html", {
        "form": form,
        "orders": orders,
        "profile": profile,
        "goto_allergens": "_allergens" in request.POST,
    })
    return result


def logout_user(request):
    logout(request)
    return redirect(request.GET.get("next", "/"))


def get_role(user, restaurant_id, rolestr):
    """return the waiter/manager's role at given restaurant or raise a HTTP exception"""
    assert rolestr in (UserRole.WAITER, UserRole.MANAGER)
    role = UserRole.objects.filter(user=user, role__name__icontains=rolestr, restaurant__id=restaurant_id).first()
    if not role:
        raise Http404("You are not registered as %s at the restaurant (id=%s)" % (rolestr, restaurant_id))
    return role

main/templates/customer/check-in.html
{% extends 'main/base.html' %}

{% block title %}Check-in at {{restaurant.name}} {% endblock %}

{% block content %}
<div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <h2>Check in at {{restaurant.name}}</h2>
        Supported payment methods are:
        <ul>
        {% for m in restaurant.payment_method.all %}
            <li>{{ m.name }}
        {% endfor %}
        </ul>
        <p>Please show this to the waiter in the restaurant. He will check you in and enable ordering from your smartphone.</p>
        <div class="col-sm-offset-3">
                <img alt="qr code" src="/media/qr/{{request.user.id}}.png">
        </div>
        Alternatively you can just <a href="{% url 'customer:menu' restaurant.id %}">browse the menu card</a>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script>
(function worker() {
    $.ajax({
        type: "GET",
        url: "{% url 'customer:check_for_open_order' restaurant.id %}",
        success: function(data, textStatus) {
            if (data != "") {
                window.location.href = "{% url 'customer:menu' restaurant.id %}";
            }
        },
        complete: function() {
            setTimeout(worker, 3000);
        }
    });
})();
</script>

{% endblock %}

main/templates/customer/checkout.html
{% extends 'main/base.html' %}

{% block title %}Check-out from {{ order.table.restaurant.name }} {% endblock %}

{% block content %}
<div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <h2>Checkout</h2>
        <p>You are about to pay and checkout. Your bill is <b>{{ order.total_confirmed }} {{ order.currency }}</b>. Please select the mode of payment. After paying you won't be able to order anymore, unless you check-in with a waiter again.</p>
            {% for m in payment_methods %}
                <a class="btn btn-primary" href="{% url 'customer:pay' order.id m.id %}">{{ m.name }}</a><br>
            {% endfor %}
        {# XXX what if there are no payment methods ? #}
    </div> 
</div>


{% endblock %}

main/templates/customer/feedback.html
{% extends 'main/base.html' %}

{% block title %}Feedback{% endblock %}

{% block content %}
<div class="container">
    <h1>Feedback</h1>
    <div class="col-sm-8 col-sm-offset-2">
        Your order at {{ order.table.restaurant.name }}, date of checkout: {{ order.checkout }}

        <table border=1>
            <tr>
                <th>Item</th>
                <th>Rating</th>
                <th>Feedback</th>
                <th></th>
            </tr>
            {% for oi in orderitems %}
    <form action="{% url 'customer:feedback' order.id %}" method="POST">
        {% csrf_token %}
                <tr>
                    <input name="id" type="hidden" value="{{ oi.id }}">
                    <td><div><b>{{ oi.name }}</b></div>
                        <img width="150" height="150" src="{{ oi.item.image.url }}">
                    </td>
                    <td><input name="rating" value="{{ oi.review.rating }}" placeholder="Rating: 1-5" {{ oi.review|yesno:"disabled,,"}}></td>
                    <td>
                        <textarea name="text" placeholder="Feedback ..." {{ oi.review|yesno:"disabled,,"}}>{{ oi.review.text }}</textarea>
                    </td>
                    <td>
                        {% if oi.review %}
                            Feedback provided on {{ oi.review.date }}.
                        {% else %}
                            <button href="#" class="btn btn-primary">Submit feedback</button>
                        {% endif %}
                    </td>
                </tr>
        </form>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

main/templates/customer/index.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block title %}SmartMenu{% endblock %}                    

{% block content %}
<div class="container">
    <div class="text-center row">
        <div class="col-sm-8 col-sm-offset-2">
            <h1>SmartMenu</h1>
            <p class="logo-lead">Bringing the restaurant to your smartphone</p>
                <form class="searchform">
                    <div class="form-group">
                        <input autocomplete="off" id="searchinput" name="q" type="search" class="form-control" placeholder="Please enter the restaurant's name" />
                    </div>
                    <div id="searchlist" class="list-group"></div>
                </form>
        </div>
    </div>

    {% if manager_at %}
    <div class="text-center row">
        You are manager at:
        {% for m in manager_at %}
            <a href="{% url 'manager:for_restaurant' m.restaurant.id %}">{{ m.restaurant.name }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    {% if waiter_at %}
    <div class="text-center row">
        You are waiter at:
        {% for w in waiter_at %}
            <a href="{% url 'waiter:for_restaurant' w.restaurant.id %}">{{ w.restaurant.name }}</a>{% if not forloop.last %}, {% endif %}
            {# XXX add template tag for: forloop.last -> , #}
        {% endfor %}
    </div>
    {% endif %}

</div>


{% endblock %}

{% block bootstrap3_extra_script %}
    <script src="{% static 'js/bootstrap-list-filter.src.js' %}"></script>

    <script>
    $('#searchlist').btsListFilter('#searchinput', {
        {# XXX any way to use django's url in conjuction with jquery's templating below? #}
        sourceTmpl: '<a class="list-group-item" href="restaurant/{id}/menu"><span><b>{name}</b>, <i>{street} {street_no}, {city}</i></span></a>',
        resetOnBlur: false,
        cancelNode: false, //XXX add cancel node that works
        sourceData: function(text, callback) {
            return $.getJSON('{% url 'customer:restaurant_search' %}?q='+text, function(json) {
                callback(json);
            });
        }
    });
 
    </script>
{% endblock %}

main/templates/customer/menu.html
{% extends 'main/base.html' %}

{% load i18n %}

{% block title %}Menu for {{ restaurant.name }} {% endblock %}

{% block content %}

<script>
$(document).ready(function() {
    $("body").tooltip({ selector: '[data-toggle=tooltip]' });
});

function imgError(image) {
    image.onerror = "";
    image.style.width = "300px";
    image.style.height = "300px";
    return true;
}
</script>

    <div class="container" id="menu">
        <!-- restaurant info -->
        <div class="row">
            <div class="info">
                <a class="anchor" name="head"></a>
                <h1 class="restaurant-name">{{ restaurant.name }} </h1>

                {% if not order %}
                <a href="{% url 'customer:check_in' restaurant.id %}" class="btn btn-sm btn-success">check-in</a>
                {% endif %}

                <p>{{ restaurant.address.street}} {{ restaurant.address.street_no}}, {{ restaurant.address.zip }}
                    {{ restaurant.address.city }}, {{ restaurant.address.country.name }}</p>

                <!-- list of categories -->
                <ul class="category-list">
                    {% for cat18n, data in categories %}
                        <li>{%if not forloop.first%}|{%endif%} <a href="#c{{cat18n.category.id}}">{{cat18n.name}}</a></li>
                    {% endfor%}
                </ul>
            </div>
        </div>


        <div class="row">
           {% for cat18n, itemdata in categories %}
            <div class="category {{cat18n.category.view.name}}">
                <a class="anchor" name="c{{cat18n.category.id}}"></a>
                <h2 class="category-header">{{ cat18n.name }} <a href="#head"><span class="link-to-head glyphicon glyphicon-triangle-top"></span></a></h2>

                <div class="category-items">
                {% for i, i18n, allergens, traces in itemdata %}
                    <div class="item">
                        <div class="item-body">
                            <div class="header">
                                <div class="name">
                                    <em>{% if menu.show_numbers%}{{ i.no }}. {% endif %}{{ i18n.name }}</em>
                                </div>
                                <div class="price">
                                    {{ i.price }} {{ i.currency.abbr }}
                                    {% if order%}
                                        <a href="{% url 'customer:order_item' restaurant.id i.id %}" class="order btn-sm btn-success">order</a>
                                    {% endif %}
                                </div>
                            </div>

                            <img src="{{ i.image.url }}" class="img-responsive" onerror="imgError(this);"/>

                            <div class="description">{{ i18n.description}}</div>

                            <div class="allergens">
                                {% language language.abbr %}
                                {%if allergens%}
                                    {% trans "Allergens" %}:
                                {%endif%}

                                {% for a18n, warn in allergens %}
                                    <span class="allergen-icon {{warn|yesno:'warn,,'}}" data-toggle="tooltip"
                                          data-original-title="{{a18n.name}}">{{a18n.allergen.no}}</span>
                                        <span class="allergen {{warn|yesno:'warn,,'}}">{{ a18n.name }}{% if not forloop.last %}, {%else%}.{%endif%}</span>
                                {% endfor %}

                                {%if traces%}
                                    <span class="traces">{% trans "May contain traces of" %}:</span>
                                {%endif%}

                                {% for a18n, warn in traces %}
                                    <span class="allergen-traces-icon {{warn|yesno:'warn,,'}}" data-toggle="tooltip"
                                          data-original-title="{{a18n.name}}">{{a18n.allergen.no}}</span>
                                    <span class="allergen-traces {{warn|yesno:'warn,,'}}">{{ a18n.name }}{% if not forloop.last%},{%else%}.{%endif%}</span>
                                {% endfor %}
                                {% endlanguage %}
                            </div>

                            <div class="clearfix"></div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
{% endblock %}

main/templates/customer/order.html
{% extends 'main/base.html' %}

{% block title %}Order{% endblock %}

{% block content %}
<div class="container">

    <h3>Invoice</h3>

    {% if not confirmed and unconfirmed %}
    <p>Your invoice is empty. Please confirm the items from the list below.
    </p>
    {% endif %}

    {% if not confirmed and not unconfirmed %}
    Your invoice is empty and you have not selected any items from the <a
        href="{% url 'customer:menu' restaurant.id %}">menu</a> yet. Please:
    <ul>
        <li>go to the menu and order some items</li>
        <li>or click <a href="{% url 'customer:checkout' order.id %}">checkout</a> to close your invoice and check out.</li>
    </ul>
    {% endif %}

    <table border="0" class="table">
        {% for oi, i18n in confirmed %}
        <tr>
            <td style="text-right">{{oi.amount}} x</td>
            <td>{{i18n.name}}</td>
            <td style="text-right">à</td>
            <td>{{oi.item.price}} {{order.currency}}</td>
            <td>{{oi.comment}}</td>
        </tr>
        {% endfor %}
        {% if confirmed %}
        <tr>
            <td></td>
            <td colspan="2">Total:</td>
            <td colspan="3"><b>{{order.total_confirmed}} {{order.currency}}</b></td>
        </tr>
        {% endif %}
    </table>


    {% if unconfirmed %}
    <h3>Items to be confirmed</h3>

    <table id="cart" class="table table-hover table-condensed" border="0">
        <thead>
        <tr>
            <th>Quantity</th>
            <th>Name</th>
            <th>Price</th>
            <th>Subtotal</th>
            <th>Comment</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for oi, i18n in unconfirmed %}
        <form action="{% url 'customer:confirm_orderitem' oi.instance.id %}" method="POST">
            {%csrf_token%}
            <tr>
                <td>
                    {{oi.amount}}
                </td>
                <td>
                    {{ i18n.name}}
                </td>
                <td>{{ oi.instance.item.price }} {{ order.currency }}</td>
                <td>{{ oi.instance.subtotal }} {{ order.currency }}</td>
                <td>{{oi.comment}}</td>
                <td>
                    <button class="btn btn-primary">confirm</button>
                    <a href="{% url 'customer:remove_orderitem' oi.instance.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        </form>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}

    <p><a href="{% url 'customer:menu' restaurant.id %}" class="btn btn-primary">Continue Ordering</a></p>
    <p><a href="{% url 'customer:checkout' order.id %}" class="btn btn-success">
        {% if confirmed %}
        Pay & Checkout
        {% else %}
        Checkout
        {% endif %}
    </a>
    </p>

</div>


{% endblock %}

main/templates/customer/paid.html
{% extends 'main/base.html' %}

{% block title %}Goodbye{% endblock %}                    

{% block content %}
<div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <p>Thank you for your payment. Please <a href="{% url 'customer:feedback' order.id %}">review</a> the food you ordered. See you soon at <b>{{ restaurant.name }}</b> and have a nice day.</p>
    </div> 
</div>


{% endblock %}