customer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^restaurant/(\d+)/order$", views.order, name="order"),
    url(r"^orderitem/(\d+)/confirm$", views.confirm_orderitem, name="confirm_orderitem"),
    url(r"^orderitem/(\d+)/remove", views.remove_orderitem, name="remove_orderitem"),
    url(r"^order/(\d+)/checkout$", views.checkout, name="checkout"),
    url(r"^order/(?P<order_id>\d+)/pay/(?P<payment_method_id>\d+)$", views.pay, name="pay"),
    url(r"^order/(\d+)/feedback$", views.feedback, name="feedback"),
    url(r"^restaurant/(?P<restaurant_id>\d+)/check-in$", views.check_in, name="check_in"),
    url(r"^restaurant/(?P<restaurant_id>\d+)/order/(?P<item_id>\d+)$", views.order_item, name="order_item"),
    url(r"^restaurant/(\d+)/menu$", views.menu, name="menu"),

    # AJAX handlers
    url(r"^restaurant/(?P<id>\d+)/check-for-order$", views.check_for_open_order, name="check_for_open_order"),
    url(r"^restaurant/search$", views.search, name="restaurant_search"),

]

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r"^register$", views.register, name="register"),
    url(r"^profile$", views.profile, name="profile"),
    url(r"^profile/delete$", views.profile_delete, name="profile_delete"),
    url(r"^logout$", views.logout_user, name="logout"),

    # AJAX stuff
    url(r"^profile/menu_languages/ordering$", views.set_menu_language_order, name="set_menu_language_order"),
]

smartmenu/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="accounts")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^main/', include('main.urls', namespace="main")),
    url(r'^customer/', include('customer.urls', namespace="customer")),
    url(r'^waiter/', include('waiter.urls', namespace="waiter")),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('customer:index'), permanent=False)),
)

main/forms.py
import imghdr
from django import forms
from django.contrib.auth.models import User
from models import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")


class UserProfileForm(forms.ModelForm):
    allergens = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = UserProfile
        fields = ("allergens",)

    def save(self, *args, **kw):
        profile = UserProfile.for_user(self.user)
        allergen_ids = self.cleaned_data.get("allergens", ())
        # convert to objects
        allergens = map(lambda x: AllergenI18n.objects.get(id=x).allergen, allergen_ids)
        # save allergens (many2many style)
        profile.allergens.clear()
        for a in allergens:
            profile.allergens.add(a)
        profile.save()
        return profile

    def __init__(self, user, lang, *args, **kw):
        # user is needed for save()
        self.user = user
        super(UserProfileForm, self).__init__(*args, **kw)

        # allergens
        initial = map(lambda x: x.id, UserProfile.for_user(self.user).allergens.all())
        self.fields['allergens'].initial = initial
        allergens = [(a.allergen.id, a.name) for a in AllergenI18n.objects.filter(language=lang)]
        self.fields['allergens'].choices = allergens


class RestaurantForm(forms.ModelForm):
    payment_method = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=PaymentMethod.objects.all(),
        required=True,
        label="Supported Payment Methods"
    )
    name = forms.CharField(label="Restaurant's name")

    class Meta:
        model = Restaurant
        fields = ("name", "payment_method")

    def __init__(self, *args, **kw):
        super(RestaurantForm, self).__init__(*args, **kw)
        self.fields['name'].widget.attrs["class"] = "form-control"


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ("street", "street_no", "zip", "city", "country")

    def __init__(self, *args, **kw):
        super(AddressForm, self).__init__(*args, **kw)
        for k, v in self.fields.items():
            v.widget.attrs["class"] = "form-control"


class MenuForm(forms.ModelForm):
    show_numbers = forms.BooleanField(label="Show menu item numbers before names", required=False)

    class Meta:
        model = Menu
        fields = ("currency", "language", "show_numbers")

    language = forms.ModelChoiceField(
        queryset=Language.objects.all(),
        label="Default menu language"
    )

    def __init__(self, *args, **kw):
        super(MenuForm, self).__init__(*args, **kw)
        for label in ("currency", "language"):
            self.fields[label].empty_label = None
            self.fields[label].required = False
            self.fields[label].widget.attrs["class"] = "form-control"


class _ItemForm(forms.Form):
    no = forms.CharField()
    name = forms.CharField()
    description = forms.CharField(widget=forms.Textarea, required=False)
    price = forms.FloatField()
    image = forms.ImageField()

    @staticmethod
    def save_image(item, image):
        ext = imghdr.what(image)
        # sometimes imghdr returns None, in that case keep old extension
        if ext is None:
            ext = image.name.split(".")[-1]
        item.image.save("item%d.%s" % (item.id, ext), image)
        item.save()

    @staticmethod
    def save_allergens(post_data, item):
        # XXX many assumptions here
        # save allergens
        for k, v in post_data.iteritems():
            if k.startswith("allergen_"):
                id = int(k.split("_")[1])
                if v == "none":
                    obj = ItemAllergen.objects.filter(allergen_id=id, item=item).first()
                    if obj:
                        obj.delete()
                    continue
                ia = ItemAllergen.objects.get_or_create(allergen_id=id, item=item)[0]
                ia.traces = v == "traces"
                ia.save()


class AddItemForm(_ItemForm):
    def __init__(self, menu, *args, **kw):
        super(AddItemForm, self).__init__(*args, **kw)
        # default for no
        self.fields["no"].initial = Item.next_free_no(menu)

    def save(self, category, language):
        item = Item()
        item.no = self.cleaned_data["no"]
        item.category = category
        item.price = self.cleaned_data["price"]
        item.save()
        self.save_image(item, self.cleaned_data["image"])
        item18n = ItemI18n(item=item, language=language)
        item18n.name = self.cleaned_data["name"]
        item18n.description = self.cleaned_data["description"]
        item18n.save()
        return item18n


class ManageItemForm(_ItemForm):
    def __init__(self, item18n, *args, **kw):
        super(ManageItemForm, self).__init__(*args, **kw)
        self._item18n = item18n
        self.fields["no"].initial = item18n.item.no
        self.fields["name"].initial = item18n.name
        self.fields["description"].initial = item18n.description
        self.fields["price"].initial = item18n.item.price
        self.fields["price"].label_suffix = " (%s)" % item18n.item.category.menu.currency
        self.fields["image"].initial = item18n.item.image

    def save(self, language):
        # if self._item18n is in a different language,
        # create a new instance (used when there is no item for a translation yet)
        if self._item18n.language != language:
            self._item18n = ItemI18n(language=language, item=self._item18n.item)
        # item18n and item
        self._item18n.description = self.cleaned_data["description"]
        self._item18n.name = self.cleaned_data["name"]
        self._item18n.save()
        self._item18n.item.price = self.cleaned_data["price"]
        self._item18n.item.no = self.cleaned_data["no"]
        self.save_image(self._item18n.item, self.cleaned_data["image"])
        self._item18n.item.save()
        return self._item18n


class AddCategoryForm(forms.Form):
    name = forms.CharField(required=True)
    view = forms.ModelChoiceField(
        queryset=CategoryView.objects.all(),
        required=True,
        empty_label=None,
    )

    def __init__(self, *args, **kw):
        super(AddCategoryForm, self).__init__(*args, **kw)
        for k, v in self.fields.items():
            v.widget.attrs["class"] = "form-control"


class AddTranslationForm(forms.Form):
    language = forms.ChoiceField()

    def __init__(self, menu, *args, **kw):
        super(AddTranslationForm, self).__init__(*args, **kw)
        choices = list(Language.objects.all())
        for l in menu.all_languages():
            if l in choices:
                choices.remove(l)
        self.fields["language"].choices = [(l.id, l) for l in choices]
        self.fields["language"].widget.attrs["class"] = "form-control"


class ChangeViewForm(forms.Form):
    view = forms.ModelChoiceField(
        queryset=CategoryView.objects.all(),
        required=True,
        empty_label=None,
    )

    def __init__(self, category, *args, **kw):
        super(ChangeViewForm, self).__init__(*args, **kw)
        self.fields["view"].widget.attrs["class"] = "form-control"
        self.fields['view'].initial = category.view


class TableForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ["no", "description"]

    def __init__(self, *args, **kw):
        super(TableForm, self).__init__(*args, **kw)
        for k, v in self.fields.items():
            v.widget.attrs["class"] = "form-control"


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ("amount", "comment",)

    comment = forms.CharField(widget=forms.TextInput, required=False)

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from main.forms import *


def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            # create user and his profile
            user = form.save()
            user.set_password(user.password)
            user.save()
            profile = UserProfile.for_user(user)
            profile.user = user
            profile.save()
            # auth created user
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'],
                                )
            login(request, user)
            return redirect("main:profile")
    else:
        form = UserForm()
    return render(request, 'main/register.html', {"userform": form})


@login_required
def set_menu_language_order(request):
    """set the ordering field for languages"""
    profile = UserProfile.for_user(request.user)
    order = request.POST.get("menu_language_order")
    profile.menu_language_order = order
    profile.save()
    return HttpResponse("")


@login_required
def profile_delete(request):
    if request.POST and "_delete" in request.POST:
        UserProfile.for_user(request.user).delete()
        request.user.delete()
        return redirect("customer:index", next=None)
    return render(request, "main/profile_delete.html")


@login_required
def profile(request):
    # default form data (GET)
    # find all orders that are finished (check_out) and sort by latest checkin date
    orders = Order.objects.filter(user=request.user, checkout__isnull=False).order_by("-checkin")

    lang = Language.get_current()
    form = UserProfileForm(request.user, lang)

    # is there data to save? (POST)
    if request.POST:
        form = UserProfileForm(request.user, lang, request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:profile")

    result = render(request, "main/profile.html", {
        "form": form,
        "orders": orders,
        "profile": profile,
        "goto_allergens": "_allergens" in request.POST,
    })
    return result


def logout_user(request):
    logout(request)
    return redirect(request.GET.get("next", "/"))


def get_role(user, restaurant_id, rolestr):
    """return the waiter/manager's role at given restaurant or raise a HTTP exception"""
    assert rolestr in (UserRole.WAITER, UserRole.MANAGER)
    role = UserRole.objects.filter(user=user, role__name__icontains=rolestr, restaurant__id=restaurant_id).first()
    if not role:
        raise Http404("You are not registered as %s at the restaurant (id=%s)" % (rolestr, restaurant_id))
    return role

main/templates/main/base.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block bootstrap3_title %}
    {% block title %}SmartMenu{% endblock %}
{% endblock %}

{% block bootstrap3_content %}
	
	{% include 'main/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'main/footer.html' %}

{% endblock %}

main/templates/main/footer.html
<footer class="footer">
    <div class="container">
        <ul class="list-inline">
            <li><a href="mailto:martin.uzak@gmail.com">&copy; 2016 Martin Užák</a></li>
            <!--
            <li><a href="#">about</a></li>
            <li><a href="#">cookie and privacy policy</a></li>
            <li><a href="#">contact</a></li>
            -->
        </ul>
    </div>
</footer>

main/templates/main/header.html
{% load smartmenu_tags %}
{% load i18n %}

<!-- Static navbar -->
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    {% if not hide_logo %}
                        {% block home_link %}
                        <a href="{% url 'customer:index' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"/></a>
                        {% if restaurant and order and not order.is_closed %}
                            <a href="{% url 'customer:menu' restaurant.id %}">{{restaurant.name}}</a>
                        {% elif restaurant%}
                            <a href="{% url 'customer:menu' restaurant.id %}">{{restaurant.name}}</a>
                    {% endif %}
                        {% endblock home_link %}
                    {% if order and not order.is_closed %}
                    <a class="btn btn-sm btn-success" href="{% url 'customer:order' order.table.restaurant.id %}">
                        <i class="glyphicon glyphicon-shopping-cart"></i>
                            {{ order.total }} {{ order.currency }}</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if menu_languages %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{% trans "Menu Language" %}: {{ language.name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for lang in menu_languages %}
                                <li><a href="{% url 'customer:menu' restaurant.id %}?l={{lang.abbr}}">{{ lang.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'accounts:login' %}">{% trans "Login" %}</a></li>
                    {% else %}
                        <p class="navbar-text">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Signed in as" %}: {{ user.first_name }} {{ user.last_name }} ({{ user.username }})<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'main:profile' %}">{% trans "Profile" %}</a></li>
                                <li><a href="{% url 'main:logout' %}?next={{request.path}}">{% trans "Logout" %}</a></li>
                            </ul>
                        </li>
                        </p>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</header>

main/templates/main/profile.html
{% extends 'main/base.html' %}

{% load staticfiles %}
{% load smartmenu_tags %}

{% block title %} My Profile {% endblock %}

{% block content %}
<div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>My Profile</h1>

        {{ form.errors }}

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#general" aria-controls="general" role="tab" data-toggle="tab">General</a>
            </li>
            <li role="presentation">
                <a href="#allergens" aria-controls="allergens" role="tab" data-toggle="tab">Allergens</a>
            </li>
            <li role="presentation">
                <a href="#history" aria-controls="history" role="tab" data-toggle="tab">History of Orders</a>
            </li>
        </ul>

        <form method="POST" action="{% url 'main:profile' %}">
            {% csrf_token %}
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="general">
                    Name: {{ user.first_name }} {{ user.last_name }} <br>
                    Username: {{ user.username }}<br>
                    Email: {{ user.email }}<br>

                    <a class="btn btn-danger" href="{% url 'main:profile_delete' %}">Delete account</a>
                </div>

                <div role="tabpanel" class="tab-pane" id="allergens">
                    Please select all allergens you are allergic to:<p>
                    {{ form.allergens }}

                    <button name="_allergens" class="btn btn-primary">Save</button>
                </div>

                <div role="tabpanel" class="tab-pane" id="history">
                    <table border="1">
                        <tr>
                            <th>Date</th>
                            <th>Restaurant</th>

                            <th>Amount</th>
                            <th>View / Feedback</th>

                        </tr>
                        {% for order in orders %}
                        <tr>
                            <td>
                                {{ order.checkin|date:"Y-m-d" }}
                            </td>
                            <td>
                                {{ order.table.restaurant.name }}
                            </td>
                            <td>
                                {{ order.total }}
                                {{ order.currency }}
                            </td>
                            <td>
                                <a href="{% url 'customer:feedback' order.id %}">View / Feedback</a>
                            </td>
                        </tr>

                        {% endfor %}
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>

{% if goto_allergens %}
    <script>
        $(document).ready(function() {
            $('.nav-tabs a[href="#allergens"]').tab('show');
        });
    </script>
{% endif %}

<script>
    // save the preferred order of languages
    var el = document.getElementById("id_languages");
    var sortable = new Sortable(el, {
        dataIdAttr: "data-id",
        store: {
              get: function(sortable) {
                   var order = "{{ profile.menu_language_order }}";
                   return order.split("|");
              },
              set: function (sortable) {
                  var order = sortable.toArray();
                  $.ajax({
                      method: "POST",
                      url: "{% url 'main:set_menu_language_order' %}",
                      data: {
                          menu_language_order: order.join("|"),
                          csrfmiddlewaretoken: '{{ csrf_token }}',
                      }
                  });
                }
            },
        });

</script>
{% endblock %}

{% block bootstrap3_extra_head %}
    <script src="{% static 'js/Sortable.js' %}"></script>
{% endblock %}

main/templates/main/profile_delete.html
{% extends 'main/base.html' %}

{% block title %} My Profile {% endblock %}

{% block content %}
<div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>My Profile</h1>
        <form method="POST">
            {% csrf_token %}
            Are you really sure to delete your profile?
            <button class="btn btn-danger" name="_delete">Yes</button>
        </form>
        <a class="btn btn-primary" href="{% url 'main:profile' %}">No, return to my profile</a>
    </div>
</div>

{% endblock %}

main/templates/main/register.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="col-sm-8 col-sm-offset-2">
        <h2>Create a new user</h2>

        <form method="POST" action="">
            {% csrf_token %}
            {{userform.as_p}}
            <input type="submit">
        </form>
    </div>
</div>

{% endblock %}