customer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^restaurant/(\d+)/order$", views.order, name="order"),
    url(r"^orderitem/(\d+)/confirm$", views.confirm_orderitem, name="confirm_orderitem"),
    url(r"^orderitem/(\d+)/remove", views.remove_orderitem, name="remove_orderitem"),
    url(r"^order/(\d+)/checkout$", views.checkout, name="checkout"),
    url(r"^order/(?P<order_id>\d+)/pay/(?P<payment_method_id>\d+)$", views.pay, name="pay"),
    url(r"^order/(\d+)/feedback$", views.feedback, name="feedback"),
    url(r"^restaurant/(?P<restaurant_id>\d+)/check-in$", views.check_in, name="check_in"),
    url(r"^restaurant/(?P<restaurant_id>\d+)/order/(?P<item_id>\d+)$", views.order_item, name="order_item"),
    url(r"^restaurant/(\d+)/menu$", views.menu, name="menu"),

    # AJAX handlers
    url(r"^restaurant/(?P<id>\d+)/check-for-order$", views.check_for_open_order, name="check_for_open_order"),
    url(r"^restaurant/search$", views.search, name="restaurant_search"),

]

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r"^register$", views.register, name="register"),
    url(r"^profile$", views.profile, name="profile"),
    url(r"^profile/delete$", views.profile_delete, name="profile_delete"),
    url(r"^logout$", views.logout_user, name="logout"),

    # AJAX stuff
    url(r"^profile/menu_languages/ordering$", views.set_menu_language_order, name="set_menu_language_order"),
]

manager/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # AJAX stuff
    url(r"^menu/(?P<id>\d+)/category/ordering", views.set_category_ordering, name="set_category_ordering"),
    url(r"^category/(?P<id>\d+)/ordering", views.set_item_ordering, name="set_item_ordering"),
    url(r"^category/(?P<id>\d+)/view/(?P<view_id>\d+)", views.set_category_view, name="set_category_view"),

    # manager
    url(r"^$", views.index, name="index"),
    url(r"^restaurant/(?P<id>\d+)$", views.for_restaurant, name="for_restaurant"),
    url(r"^restaurant/create$", views.create_restaurant, name="create_restaurant"),
    url(r"^restaurant/(?P<id>\d+)/manage$", views.manage_restaurant, name="manage_restaurant"),
    url(r"^restaurant/(?P<id>\d+)/statistics$", views.statistics, name="statistics"),
    url(r"^restaurant/(?P<id>\d+)/delete", views.delete_restaurant, name="delete_restaurant"),
    url(r"^restaurant/(?P<id>\d+)/add_table$", views.add_table, name="add_table"),
    url(r"^restaurant/(?P<id>\d+)/tables$", views.table_index, name="table_index"),
    url(r"^table/(?P<id>\d+)/delete$", views.delete_table, name="delete_table"),
    url(r"^menu/(?P<id>\d+)/manage$", views.manage_menu, name="manage_menu"),
    url(r"^category/(?P<id>\d+)/manage", views.manage_category, name="manage_category"),
    url(r"^category/(?P<id>\d+)/delete", views.delete_category, name="delete_category"),
    url(r"^category/(?P<id>\d+)/rename", views.rename_category, name="rename_category"),
    url(r"^category/(?P<id>\d+)/add_item", views.add_item, name="add_item"),
    url(r"^menu/(?P<id>\d+)/category/add$", views.add_category, name="add_category"),
    url(r"^item/(?P<id>\d+)/manage$", views.manage_item, name="manage_item"),
    url(r"^item/(?P<id>\d+)/delete", views.delete_item, name="delete_item"),
    url(r"^menu/(?P<menu_id>\d+)/translation/add$", views.add_translation, name="add_translation"),
    url(r"^menu/(?P<menu_id>\d+)/translation/(?P<lang_id>\d+)/delete$", views.delete_translation,
        name="delete_translation"),
]

smartmenu/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="accounts")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^main/', include('main.urls', namespace="main")),
    url(r'^customer/', include('customer.urls', namespace="customer")),
    url(r'^waiter/', include('waiter.urls', namespace="waiter")),
    url(r'^manager/', include('manager.urls', namespace="manager")),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('customer:index'), permanent=False)),
)

main/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Max
from django.http.response import Http404
from django.utils import translation
from django_countries.fields import CountryField

RUBAXA_SORTABLE_SEP = ","


def ids(alist):
    return map(lambda x: x.id, alist)


def ordered(items, order_str, sep="|"):
    """return all items, ordered by integers in 'order_str'.
    If 'order_str' is not set, use default order"""
    # print "order_str", order_str
    if not order_str:
        return items
    # obtain ordering instructinos
    order = map(int, order_str.split(sep))
    # build a dict with IDs as keys
    tmp = {}
    for e in items:
        tmp[e.id] = e
    # make a list ordered by 'order'
    result = []
    for o in order:
        if o in tmp:
            result.append(tmp[o])
    # add omitted elements (not found in 'order_str')
    for k, v in tmp.items():
        if k not in order:
            result.insert(0, v)
    return result


def _ordering_str(data, sep=RUBAXA_SORTABLE_SEP):
    result = []
    for i in data:
        if i.ordering:
            result.append(i.ordering)
    return sep.join(map(str, result))


# Icons took from http://www.allergenchecker.co.uk/allergens.php
class Allergen(models.Model):
    no = models.PositiveSmallIntegerField()

    def __unicode__(self):
        return "Allergen (no=%d)" % self.no

    def image_uri(self):
        return "/media/allergens/%d.png" % self.no


class AllergenI18n(models.Model):
    allergen = models.ForeignKey(Allergen)
    language = models.ForeignKey("Language")
    name = models.CharField(max_length=80)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return "%d (%s)" % (self.allergen.no, self.name)

    @staticmethod
    def for_item(item, language):
        # obtains allergens as tuples: (ItemAllergen, AllergenI18n)
        allergens = AllergenI18n.objects.filter(language=language)
        allergens = [(ItemAllergen.objects.filter(item=item, allergen=a18n.allergen).first(), a18n) for a18n in
                     allergens]
        return allergens


class Currency(models.Model):
    abbr = models.CharField(max_length=16, unique=True)
    name = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name_plural = "Currencies"

    def __unicode__(self):
        return self.abbr


class Language(models.Model):
    abbr = models.CharField(max_length=16, unique=True)
    # name is in local language (i.e. deutsch, english, slovensky)
    name = models.CharField(max_length=255)

    @staticmethod
    def get_current():
        ui_lang = translation.get_language()
        return Language.objects.filter(abbr=ui_lang).first()

    def __unicode__(self):
        return "%s (%s)" % (self.abbr, self.name)

    @staticmethod
    def order(languages, order_str=None):
        """return all languages, ordered by 'language_order'.
        If 'language_order' is not set, use default order"""
        return ordered(languages, order_str)


class Menu(models.Model):
    currency = models.ForeignKey(Currency)
    language = models.ForeignKey(Language)
    restaurant = models.OneToOneField("Restaurant")
    translations = models.ManyToManyField(Language, related_name="menu_translations")
    show_numbers = models.BooleanField(default=True)

    def all_languages(self):
        result = [self.language]
        for tr in self.translations.all():
            result.append(tr)
        return result

    class Meta:
        verbose_name_plural = "Menues"

    def __unicode__(self):
        return "Menu (id=%d) for restaurant %d" % (self.id, self.restaurant.id)

    def categories_for_language(self, language):
        """return all the categories of this menu in given language, if categories in given
        language cannot be found, default to primary menu language"""
        if language not in self.all_languages():
            raise Http404("Not supported language")
        result = []
        for c in self.category_set.all():
            cat = CategoryI18n.objects.filter(language=language, category=c).first()
            if not cat:  # try default category
                cat = CategoryI18n.objects.filter(language=self.language, category=c).first()
            if not cat:  # not found for given language, not found for master language
                # print "lang", language
                # print "default lang", self.language
                # print "all category languages:", CategoryI18n.objects.filter(category = c).all()
                raise Http404("Category (%d) with no I18N" % c.id)
            result.append(cat)
        result = sorted(result, lambda x, y: cmp(x.category.ordering, y.category.ordering))
        return result

    def category_ordering_str(self, sep=RUBAXA_SORTABLE_SEP):
        return _ordering_str(self.category_set.all(), sep=sep)


class Category(models.Model):
    """Category of a menu card"""

    menu = models.ForeignKey(Menu)
    ordering = models.SmallIntegerField(blank=True, null=True)
    view = models.ForeignKey("CategoryView")

    class Meta:
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return "Category: (id=%d)" % self.id

    def item_ordering_str(self, sep=RUBAXA_SORTABLE_SEP):
        return _ordering_str(self.item_set.all(), sep=sep)

    def items_for_language(self, language):
        """return all the items of this category in given language, if items in given
        language cannot be found, default to primary menu language"""
        if language not in self.menu.all_languages():
            raise Http404("Not supported language")
        result = []
        for i in self.item_set.all():
            item = ItemI18n.objects.filter(language=language, item=i).first()
            if not item:  # try default language
                item = ItemI18n.objects.filter(language=self.menu.language, item=i).first()
            if not item:  # not found for given language, not found for master language
                raise Http404("Item (%d) with no I18N" % i.id)
            result.append(item)
        result = sorted(result, lambda x, y: cmp(x.item.ordering, y.item.ordering))
        return result


class CategoryI18n(models.Model):
    category = models.ForeignKey(Category)
    language = models.ForeignKey(Language)
    name = models.CharField(max_length=255)

    def __init__(self, *args, **kw):
        super(CategoryI18n, self).__init__(*args, **kw)
        # In case a category hasn't been translated yet, master's language category is used. In this
        # case we mark the object as not translated.
        self.translated = True

    @staticmethod
    def get_for_language(language, cat):
        """try to obtain the CategoryI18n for given 'language'.
        If language is not found, try master language. Otherwise fail
        """
        for lang in (language, cat.menu.language):
            cat18n = CategoryI18n.objects.filter(language=lang, category=cat).first()
            if cat18n:
                return cat18n
        raise Http404("ItemI18N not found for language (%s) and Item (%d)" % (language.abbr, cat.id))

    def __unicode__(self):
        return "%s (Cat: %d, lang: %s)" % (self.name, self.category.id, self.language.abbr)


class Item(models.Model):
    """a MenuItem"""
    no = models.PositiveSmallIntegerField(null=True, blank=True)
    price = models.FloatField()
    category = models.ForeignKey(Category)
    ordering = models.SmallIntegerField(blank=True, null=True)
    image = models.ImageField(upload_to="items/")

    # used in the admin (preview of the image)
    def image_preview(self):
        return '<img src="%s" />' % (self.url())

    image_preview.allow_tags = True

    @staticmethod
    def next_free_no(menu):
        result = Item.objects.filter(category__menu=menu).aggregate(Max("no"))["no__max"]
        if result:
            return result + 1
        return 1

    def currency(self):
        return self.category.menu.currency

    def __unicode__(self):
        return "Item (id=%d)" % self.id


# http://stackoverflow.com/questions/5372934/how-do-i-get-django-admin-to-delete-files-when-i-remove-an-object-from-the-datab
# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
import os


@receiver(pre_delete, sender=Item)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)


@receiver(models.signals.pre_save, sender=Item)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes image from filesystem
    when corresponding `Item` object is changed.
    """
    if not instance.pk:
        return False

    try:
        old_file = Item.objects.get(pk=instance.pk).image
    except Item.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        try:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)
        except Exception:
            return False


class ItemI18n(models.Model):
    item = models.ForeignKey(Item)
    language = models.ForeignKey(Language)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    def __init__(self, *args, **kw):
        super(ItemI18n, self).__init__(*args, **kw)
        # In case an item hasn't been translated yet, master's language item is used. In this
        # case we mark the object as not translated in views.py.
        self.translated = True

    @staticmethod
    def get_for_language(language, item):
        """try to obtain the ItemI18N for given 'language'.
        If language is not found, try master language. Otherwise fail"""
        for lang in (language, item.category.menu.language):

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from main.forms import *


def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            # create user and his profile
            user = form.save()
            user.set_password(user.password)
            user.save()
            profile = UserProfile.for_user(user)
            profile.user = user
            profile.save()
            # auth created user
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'],
                                )
            login(request, user)
            return redirect("main:profile")
    else:
        form = UserForm()
    return render(request, 'main/register.html', {"userform": form})


@login_required
def set_menu_language_order(request):
    """set the ordering field for languages"""
    profile = UserProfile.for_user(request.user)
    order = request.POST.get("menu_language_order")
    profile.menu_language_order = order
    profile.save()
    return HttpResponse("")


@login_required
def profile_delete(request):
    if request.POST and "_delete" in request.POST:
        UserProfile.for_user(request.user).delete()
        request.user.delete()
        return redirect("customer:index", next=None)
    return render(request, "main/profile_delete.html")


@login_required
def profile(request):
    # default form data (GET)
    # find all orders that are finished (check_out) and sort by latest checkin date
    orders = Order.objects.filter(user=request.user, checkout__isnull=False).order_by("-checkin")

    lang = Language.get_current()
    form = UserProfileForm(request.user, lang)

    # is there data to save? (POST)
    if request.POST:
        form = UserProfileForm(request.user, lang, request.POST)
        if form.is_valid():
            form.save()
            return redirect("main:profile")

    result = render(request, "main/profile.html", {
        "form": form,
        "orders": orders,
        "profile": profile,
        "goto_allergens": "_allergens" in request.POST,
    })
    return result


def logout_user(request):
    logout(request)
    return redirect(request.GET.get("next", "/"))


def get_role(user, restaurant_id, rolestr):
    """return the waiter/manager's role at given restaurant or raise a HTTP exception"""
    assert rolestr in (UserRole.WAITER, UserRole.MANAGER)
    role = UserRole.objects.filter(user=user, role__name__icontains=rolestr, restaurant__id=restaurant_id).first()
    if not role:
        raise Http404("You are not registered as %s at the restaurant (id=%s)" % (rolestr, restaurant_id))
    return role

main/templates/manager/header.html
{% extends 'main/header.html' %}

{% block home_link %}
<a href="{% url 'customer:index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"/></a>

{% if restaurant %}
<ol class="breadcrumb" style="display: inline;">
    <li><a href="{% url 'manager:for_restaurant' restaurant.id %}">{{restaurant.name}}</a></li>
    <li><a href="{% url 'manager:manage_menu' restaurant.menu.id %}">Menu</a></li>

    {% if cat18n %}
    <li><a href="{% url 'manager:manage_category' cat18n.category.id %}">{{cat18n.name}}</a></li>

        {% if item18n %}
        <li><a href="{% url 'manager:manage_item' item18n.item.id %}">{{item18n.item.no}}</a></li>
        {% endif %}

    {% endif%}
</ol>
{% endif%}


{% endblock %}

main/templates/manager/index.html
{% extends 'manager/base.html' %}

{% load staticfiles %}


{% block title %}SmartMenu / Manager {% endblock %}

{% block content %}
<div class="container">
    <p>
    <h1 style="display: inline">{{restaurant.name}}</h1>
    {% if show_change_restaurant %}
    <a href="{% url 'manager:index' %}">change restaurant</a>
    {% endif %}
    </p>

    <p>
    <a href="{% url 'manager:manage_restaurant' restaurant.id %}" class="btn btn-primary">Manage Restaurant</a>
        Change restaurant's name or address?
    </p>

    <p>
    <a href="{% url 'manager:manage_menu' restaurant.menu.id %}" class="btn btn-primary">Manage Menu</a>
    </p>

    <p>
        <a href="{% url 'manager:table_index' restaurant.id %}" class="btn btn-primary">Manage tables</a>
    </p>

    <p>
    <a href="{% url 'manager:delete_restaurant' restaurant.id %}" class="btn btn-danger">Delete restaurant</a>
        In case you want to remove restaurant from SmartMenu.
    </p>

    <p>Do you want to see the menu as your customer sees it?
    <a href="{% url 'customer:menu' restaurant.id %}" target="_blank">Show menu in new window</a>
    </p>

</div>

{% endblock %}

main/templates/manager/manage-category.html
{% extends 'manager/base.html' %}

{% load staticfiles %}


{% block title %}SmartMenu / Manage Category {% endblock %}

{% block content %}
<div class="container">

    {% if cat18n.translated %}
    <h1 class="inline">{{cat18n.name }}</h1>
    {% else %}
    <span class="no-translation">no translation</span> ({{cat18n.language.abbr}}: {{cat18n.name}})
    {% endif %}

    {% if cat18n.translated %}
    <a href="#" data-toggle="modal" data-target="#myModal">rename</a>
    <a href="{% url 'manager:delete_category' cat18n.category.id %}" class="text-danger">delete</a>
    {% else %}
    <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#myModal">translate</a>
    {% endif %}

    {{ change_view_form.as_p}}

    <h3>Translations:</h3>
    <table class="table-languages">
        {% for lang, current, cat18n in languages %}
        <tr>
            <td>{% if current %}<b>{{lang}}</b> {% else %} <a
                    href="{% url 'manager:manage_category' cat.id %}?l={{lang.abbr}}">{{lang}}</a> {% endif%}
            </td>
            <td>{% if cat18n %}
                {{cat18n.name}}
                {% else %}
                <span class="no-translation">missing translation</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    <hr>

    <h2>Items</h2>
    {% if items %}
    Use drag and drop to change oder. Click an item to rename, delete or manage it.
    <ul id="id_items">
        {% for i in items %}
        <li data-id="{{ i.item.id }}"><a href="{% url 'manager:manage_item' i.item.id %}">{{ i.name }}</a>
            {% endfor %}
    </ul>
    {% endif %}

    <a href="{% url 'manager:add_item' cat.id %}" class="btn btn-primary">Add item</a>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form action="{% url 'manager:rename_category' cat.id %}" method="POST">
            <div class="modal-content">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Rename category {{cat18n.name}}</h4>
                </div>
                <div class="modal-body">
                    <input name="name" class="form-control" value="{{cat18n.name}}">
                    <input name="language" type="hidden" value="{{language.abbr}}">
                </div>
                <div class="modal-footer">
                    <a type="button" class="btn btn-default" data-dismiss="modal">Close</a>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    // change view
    $("#id_view").change(function() {
        var value = $(this).val();
        var url = "{% url 'manager:set_category_view' cat18n.category.id 0 %}";
        url = url.slice(0, -1) + value;
        $.get(url, function(res){
            // pass
        });
    });


    // item ordering
    var el = document.getElementById("id_items");
    var sortable = new Sortable(el, {
        dataIdAttr: "data-id",
        store: {
              get: function(sortable) {
                   var order = "{{ ordering }}";
              },
              set: function (sortable) {
                  var order = sortable.toArray();
                  $.ajax({
                      method: "POST",
                      url: "{% url 'manager:set_item_ordering' cat.id %}",
                      data: {
                          item_ordering: order.join("|"),
                          csrfmiddlewaretoken: '{{ csrf_token }}',
                      }
                  });
                }
            },
        });


</script>
{% endblock %}

{% block bootstrap3_extra_head %}
<script src="{% static 'js/Sortable.js' %}"></script>
{% endblock %}

main/templates/manager/manage-item.html
{% extends 'manager/base.html' %}

{% load staticfiles %}

{% block title %}SmartMenu / Manager / Item {% endblock %}

{% block content %}
<div class="container">

    {% if item18n.translated %}
    <h1 class="inline">{{ item18n.name }}</h1>
    {% else %}
    <span class="no-translation">Item is not yet translated to {{language.name}}.</span><br>Translate it by changing the name and description in the table below and clicking the save button.
    {% endif %}

    {% if item18n.translated %}
    <a href="{% url 'manager:delete_item' item18n.item.id %}" class="text-danger">delete</a>
    {% endif %}

    <h3>Translations:</h3>
    <table class="table-languages">
        {% for lang, current, translation in languages %}
        <tr>
            <td>{% if current %}<b>{{lang}}</b> {% else %} <a
                    href="{% url 'manager:manage_item' item18n.item.id %}?l={{lang.abbr}}">{{lang}}</a> {% endif%}
            </td>
            <td>{% if translation %}
                {{translation.name}}
                {% else %}
                <span class="no-translation">missing translation</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    <hr>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <table class="item-table">
            <tr>
                <th>{{ form.no.label }} {{ form.no.errors}}</th>
                <td>{{ form.no }}</td>
            </tr>
            <tr>
                <th>{{ form.name.label }}</th>
                <td {% if not item18n.translated %} class="change-this" {% endif %}>{{ form.name }}</td>
            </tr>
            <tr>
                <th>{{ form.description.label }}</th>
                <td {% if not item18n.translated %} class="change-this" {% endif %}>{{ form.description }}</td>
            </tr>
            <tr>
                <th>{{ form.price.label }} {{ form.price.errors}}</th>
                <td>{{ form.price }}</td>
            </tr>
            <tr>
                <th>{{ form.image.label }} {{ form.image.errors}}</th>
                <td>{{ form.image }}</td>
            </tr>
            <tr><td>
                <button class="btn btn-primary">Save</button>
            </td></tr>
        </table>


        <div class="manage-allergens">
            <h3>Allergens</h3>
            <table>
                <tr>
                    <th>Full</th>
                    <th>Traces</th>
                    <th>No</th>
                    <th>Name</th>
                </tr>
            {% for ai, a18n in allergens %}
                <tr>
                    <td>
                        <input type="radio" name="allergen_{{a18n.allergen.id}}" value="full" {{ ai.traces|yesno:',checked,'}}>
                    </td>
                    <td>
                        <input type="radio" name="allergen_{{a18n.allergen.id}}" value="traces" {{ ai.traces|yesno:'checked,,'}}>
                    </td>
                    <td>
                        <input type="radio" name="allergen_{{a18n.allergen.id}}" value="none" {{ ai|yesno:',,checked'}}>
                    </td>
                    <td>{{a18n.name}}</td>
                </tr>
            {% endfor%}
            </table>
        </div>
    </form>
</div>

{% endblock %}

main/templates/manager/manage-menu.html
{% extends 'manager/base.html' %}

{% load staticfiles %}

{% block title %}SmartMenu / Manage Menu {% endblock %}

{% block content %}
<div class="container manage-menu">
    <h1>Menu</h1>
    <form method="POST">
        {% csrf_token %}

        <!-- Changing a menu's default language is not supported yet. But you might add a new Translation,
        see "Translation" section below.-->
        {{ form.as_p }}
        <button class="btn btn-primary">Save</button>

        {% if menu %}
            <h3>Categories</h3>
            {% if categories %}

            Use drag and drop to change the order of categories. To manage a category (incl, renaming and deleting) click the link.

            <ul id="id_categories">
            {% for cat in categories %}
                <li data-id="{{cat.category.id}}">
                    <a href="{% url 'manager:manage_category' cat.category.id %}">{{ cat.name }}</a>
                </li>
            {% endfor %}
            </ul>
            {% endif %}

            <a class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm" href="#">Add new category</a>

            <h3>Translations</h3>

            <ul>
                {% for tr in menu.translations.all %}
                    <li>{{ tr }} <a href="{% url 'manager:delete_translation' menu.id tr.id %}">remove</a></li>
                {% endfor %}
            </ul>

            <a href="#" data-target=".bs-example-modal-sm2" data-toggle="modal" class="btn btn-primary">Add new translation</a>
        {% endif %}
    </form>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <form action="{% url 'manager:add_category' menu.id %}" method="POST">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add new category</h4>
                </div>
                <div class="modal-body">
                    <p>Add a new category to your menu. E.g.: soups, main dishes, appetisers, etc.</p>
                    <p>View determines how the items of a category will be displayed in the menu.</p>
                    {{ add_cat_form }}
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal">Close</a>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade bs-example-modal-sm2" tabindex="-1" role="dialog" aria-labelledby="languageModal">
    <div class="modal-dialog" role="document">
        <form action="{% url 'manager:add_translation' menu.id %}" method="POST">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="languageModalLabel">Add new translation</h4>
                </div>
                <div class="modal-body">
                    <p>After adding a translation you will be able to translate your menu into that language.</p>
                    {{ add_translation_form }}
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal">Close</a>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    // disable language
    $('#id_language').prop('disabled', true);

    // drag and drop categories
    var el = document.getElementById("id_categories");
    var sortable = new Sortable(el, {
        dataIdAttr: "data-id",
        store: {
              get: function(sortable) {
                   var order = "{{ ordering }}";
              },
              set: function (sortable) {
                  var order = sortable.toArray();
                  $.ajax({
                      method: "POST",
                      url: "{% url 'manager:set_category_ordering' menu.id %}",
                      data: {
                          category_ordering: order.join("|"),
                          csrfmiddlewaretoken: '{{ csrf_token }}',
                      }
                  });
                }
            },
        });
</script>
{% endblock %}

{% block bootstrap3_extra_head %}
    <script src="{% static 'js/Sortable.js' %}"></script>
{% endblock %}